# Generated by Django 5.0.1 on 2025-12-15 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, help_text='URL de la vidéo de présentation', verbose_name='URL vidéo (YouTube/Vimeo)')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Mots-clés')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('author_location', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Note sur 5', verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Courriel')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_type', models.CharField(choices=[('contact', 'Contact général'), ('purchase', "Demande d'achat")], default='contact', max_length=20, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('last_email_status', models.BooleanField(blank=True, help_text='True si le dernier email a été envoyé avec succès, False sinon', null=True, verbose_name='Email envoyé avec succès')),
                ('last_email_datetime', models.DateTimeField(blank=True, help_text="Date et heure de la dernière tentative d'envoi d'email", null=True, verbose_name='Date dernier email')),
                ('last_email_error', models.TextField(blank=True, help_text="Message d'erreur de la dernière tentative d'envoi d'email", verbose_name='Erreur dernier email')),
                ('last_email_traceback', models.TextField(blank=True, help_text="Traceback complet de la dernière erreur d'envoi d'email", verbose_name='Traceback dernier email')),
                ('painting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='gallery.painting', verbose_name='Toile concernée')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
