# Generated by Django 5.0.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Finition',
                'verbose_name_plural': 'Finitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='SKU')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_cad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (CAD)')),
                ('dimensions', models.CharField(help_text='Ex: 24" x 36" ou 60cm x 90cm', max_length=100, verbose_name='Dimensions')),
                ('is_active', models.BooleanField(default=True, help_text='Visible sur le site', verbose_name='Actif')),
                ('is_featured', models.BooleanField(default=False, help_text="Afficher sur la page d'accueil", verbose_name='Vedette')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendu'), ('not_for_sale', 'Non à vendre')], default='available', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paintings', to='gallery.category', verbose_name='Catégorie')),
                ('finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paintings', to='gallery.finish', verbose_name='Finition')),
            ],
            options={
                'verbose_name': 'Toile',
                'verbose_name_plural': 'Toiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaintingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='paintings/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.painting', verbose_name='Toile')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-is_primary', 'order'],
            },
        ),
    ]

