# Generated by Django 5.0.1 on 2026-02-21 18:15

import apps.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_update_painting_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Visible sur le site', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='paintingimage',
            name='image',
            field=models.ImageField(upload_to=apps.gallery.models.painting_image_upload_to, verbose_name='Image'),
        ),
    ]
